### ISSUE TITLE
Do not show alert for records made with older version of program 

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/AERCalc#13]
Program should not show alert (in error column ??) for records made in older version of the program.

There is already a column for W7 Version, so this can be used to determine certification compliance

**Comment by StephenCzarnecki** [comment]
Looking into this it seems that there is also code to show a warning if there are results from an older version of E+.  We haven't upgraded E+ yet and so that message hasn't been apparent but would be if/when we update E+.  Should it be disabled as well?

**Comment by RDmitchell** [comment]
Why don't you disable that check for now, and make a new issue for this, ie, 

* Display the E+ version on the list view (add it)
* Keep the error check disabled, with some potential for the future to be more nuanced about how we do that checking. 

Then put the issue in the Ice Box (!) column 

Thanks !

**Comment by StephenCzarnecki** [comment]
Should be fixed as of 1.3.3

**Comment by RDmitchell** [comment]
no longer relevant
