### ISSUE TITLE
Remove WQ code from AERCalc

### ISSUE THREAD

**Issue by StephenCzarnecki** [LBNL-ETA/AERCalc#20]
Window quilts are no longer getting their own product type in AERCalc so remove "WQ" from the list of valid codes.

**Comment by RDmitchell** [comment]
Just for the record, Window Quilts are going to be modeled as Roller Shades

**Comment by StephenCzarnecki** [comment]
Should be fixed as of 1.3.3

**Comment by RDmitchell** [comment]
Done
