### ISSUE TITLE
Check EPc results from 1.3.0 / WINDOW 7.8.04 for Window Panels

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/AERCalc#23]
WINDOW 7.8.04
AERCalc 1.3.0

File:
AERCalcSample.mdb
G:\Shared drives\AERCalc\Sample Database\WINDOW 7.8.04

I re-ran the Window Panels with the proper Air Leakage:
* 0.4 == Indoor case
* 0.5 == Outdoor case
![image](https://user-images.githubusercontent.com/6314950/89361373-fb16fd80-d67f-11ea-9e2f-c1aed657c99e.png)

I got different results for the EPc values than previous versions (see the master results spreadsheet), but the same values for EPh as previous versions

![image](https://user-images.githubusercontent.com/6314950/89361606-8c866f80-d680-11ea-8046-d859098fea3e.png)

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- can you take a look at the AERCalcSample database and see if I have done something wrong in my modeling of the Window Panels?

**Comment by StephenCzarnecki** [comment]
@RDmitchell I ran the window panels in the latest version of AERCalc I made using the latest sample database and WINDOW 7.8.5 and got results that match 1.2.6/1.3.x in the spreadsheet.

![image](https://user-images.githubusercontent.com/7605407/89841736-c1436c80-db41-11ea-82b0-0b9bc91d70aa.png)

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- did you change the infiltration rate for your runs?

**Comment by StephenCzarnecki** [comment]
Yes I set the first two to 0.4 and the second two to 0.5

![image](https://user-images.githubusercontent.com/7605407/89942243-35d1e600-dbea-11ea-86a4-64254900ce32.png)

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- I am rerunning mine in the latest version of AERCalc.

**Comment by RDmitchell** [comment]
AERCalc 1.3.0
WINDOW 7.8.04

I am now getting the same results as in the spreadsheet and the results from @StephenCzarnecki 
![image](https://user-images.githubusercontent.com/6314950/89942987-568e4180-dbd2-11ea-8c5a-7d23db11fb21.png)
![image](https://user-images.githubusercontent.com/6314950/89942995-5a21c880-dbd2-11ea-9be6-d509221a7399.png)
