### ISSUE TITLE
Make sure the latest version of genfmtx.exe is in install files

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/AERCalc#24]
AERCalc 1.3.0

@StephenCzarnecki -- this is for both of us. 

When you make the AIR install that I then use to make the InstallShield install, we need to make sure that the latest version of genfmtx.exe is being used. 

It is in the \W7\genBSDF folder

The latest version has a date of 6/1/2020

I have put a copy of it in this issue folder
G:\Shared drives\AERCalc\Github Issues\Issue 24

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- In my InstallShield installation file set, I don't have the following folders / files included in the "Components" that are installed. So if they are not there, where does AERCalc get them from? Seems like I should add them? I will go through all my steps to create the install, including your original installation, which probably includes all of them, I'm just not getting them into the actually InstallShield file definitions. 

* AwningBSDF
* genBSDF
* Standards
* XML

![image](https://user-images.githubusercontent.com/6314950/89581079-37b33800-d7eb-11ea-92ad-bb50f30f1a42.png)

**Comment by RDmitchell** [comment]
maybe this is why I was getting such wonky results in AERCalc

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- NEVER MIND -- it looks like I am including the W7 subfolders in my InstallShield component definition, so they will all be there. 

So back to the original issue, we just need to make sure the latest genfmtx.exe file is in your AIR install.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- I am deleting the above comments where I talk about not having the right files in the install -- it just makes this issue confusing.

**Comment by StephenCzarnecki** [comment]
Should be fixed as of 1.3.3
