### ISSUE TITLE
Open hourly data not being used in calculations for any shading products

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/AERCalc#6]
@StephenCzarnecki to investigate the issue of whether the program is using the shade open case for the hourly weighting calculations. It seems that it isn't.

**Comment by RDmitchell** [comment]
Here is the plan to deal with this:

* @StephenCzarnecki 
  * will run the base case B files for Minneapolis and Houston and save the hourly E+ files
  * Compare E+ timestep and table files with those generated by Robert (already sent to Stephen)
  * Let's put off awnings until we figure this out for other shades. Awnings definition for Open is No Shade, so the same base case runs apply to awnings
  * Change ESCALC to always use the precalculated timestep baseline E+ results
  * Add a check to make sure that the Open, Half Open and Deployed add up to 100 (this will be complicated for venetian blinds)
  * Add a check to make sure that all configurations for a shading product have E+ timestep results (ie, venetian blinds should have 8, ie, the 7 from AERCalc + 1 from Baseline) -- throw an error if this check fails
  * Run AERCalc to get results for the standard examples.
  * Provide those results to postdoc 

**Postdoc (Maryna or Yuan)**
* Robert to talk to Jacob about who should work on this
* Using AERC 2 (the official AERC document) which documents the algorithms, recreate the algorithm and produce results for the standard set of shading products that we ship with AERCalc. Any platform can be used for this (spreadsheet, MatLab, python, etc) 
* Robert will provide the output files to use for the weighting, so that they don't have to actually run the E+ files to do the calculations
* Compare results from Stephen via AERCalc to these calculations

If AERCalc results are the same as the new calculation method results, then we can assume that AERCalc is doing the correct calculation,

**Charlie**
* Work with Jallen to go over the scripts that he created that Simon is now using.

**Comment by StephenCzarnecki** [comment]
This has been resolved and I think it should be closed.

Resolution was that the open hourly data was being used in the form of a magic number.  But that magic number was based on the original weighting schedule.  So when the awnings used a different weighting schedule that magic number was no longer correct.  The implemented solution was to refactor ESCalc to take the weighting coefficient schedule and calculate the weighted open values based on that schedule.

**Comment by RDmitchell** [comment]
Thanks Stephen. Am closing
